name: smart_access
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  camera: ^0.11.1
  mime: ^1.0.0
  shared_preferences: ^2.0.15
  http: ^1.3.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  google_mlkit_face_detection: ^0.12.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  assets:
    - assets/
    - .env
